POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Aulão React Ao Vivo",
  "details": "Revisão especial de react para quem quer acelerar seu aprendizado!",
  "maximumAttendees": 2
}

###

POST http://localhost:3333/events/d052f8d5-f8ea-4928-a71f-56e2467e603b/attendees
Content-Type: application/json

{
  "name": "Bruna Terribile",
  "email": "brunaterribile@gmail.com"
}

###

GET http://localhost:3333/events/d052f8d5-f8ea-4928-a71f-56e2467e603b

###

GET http://localhost:3333/attendees/3/badge